package Modelo;
// Generated 13-mar-2016 17:18:55 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private int idPersonas;
     private String nombrePersonas;
     private String apellidoPersonas;
     private String mailPersonas;
     private Set tareases = new HashSet(0);

    public Personas() {
    }

	
    public Personas(int idPersonas) {
        this.idPersonas = idPersonas;
    }
    public Personas(int idPersonas, String nombrePersonas, String apellidoPersonas, String mailPersonas, Set tareases) {
       //this.idPersonas = idPersonas;
       this.nombrePersonas = nombrePersonas;
       this.apellidoPersonas = apellidoPersonas;
       this.mailPersonas = mailPersonas;
       this.tareases = tareases;
    }

    public Personas(String nombrePersonas, String apellidoPersonas, String mailPersonas) {
        this.nombrePersonas = nombrePersonas;
        this.apellidoPersonas = apellidoPersonas;
        this.mailPersonas = mailPersonas;
    }
    
    
   
    public int getIdPersonas() {
        return this.idPersonas;
    }
    
    public void setIdPersonas(int idPersonas) {
        this.idPersonas = idPersonas;
    }
    public String getNombrePersonas() {
        return this.nombrePersonas;
    }
    
    public void setNombrePersonas(String nombrePersonas) {
        this.nombrePersonas = nombrePersonas;
    }
    public String getApellidoPersonas() {
        return this.apellidoPersonas;
    }
    
    public void setApellidoPersonas(String apellidoPersonas) {
        this.apellidoPersonas = apellidoPersonas;
    }
    public String getMailPersonas() {
        return this.mailPersonas;
    }
    
    public void setMailPersonas(String mailPersonas) {
        this.mailPersonas = mailPersonas;
    }
    public Set getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set tareases) {
        this.tareases = tareases;
    }

    @Override
    public String toString() {
        return "Nombre: " + nombrePersonas +", Apellido: " + apellidoPersonas + ", Mail: " + mailPersonas;
    }




}


