package Modelo;
// Generated 13-mar-2016 17:18:55 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tareas generated by hbm2java
 */
public class Tareas  implements java.io.Serializable {


     private int idTareas;
     private String nombreTareas;
     private String descripcionTareas;
     private Set personases = new HashSet(0);

    public Tareas() {
    }

	
    public Tareas(int idTareas) {
        this.idTareas = idTareas;
    }
    public Tareas(int idTareas, String nombreTareas, String descripcionTareas, Set personases) {
       this.idTareas = idTareas;
       this.nombreTareas = nombreTareas;
       this.descripcionTareas = descripcionTareas;
       this.personases = personases;
    }

    public Tareas(String nombreTareas, String descripcionTareas) {
        this.nombreTareas = nombreTareas;
        this.descripcionTareas = descripcionTareas;
    }
    
    
   
    public int getIdTareas() {
        return this.idTareas;
    }
    
    public void setIdTareas(int idTareas) {
        this.idTareas = idTareas;
    }
    public String getNombreTareas() {
        return this.nombreTareas;
    }
    
    public void setNombreTareas(String nombreTareas) {
        this.nombreTareas = nombreTareas;
    }
    public String getDescripcionTareas() {
        return this.descripcionTareas;
    }
    
    public void setDescripcionTareas(String descripcionTareas) {
        this.descripcionTareas = descripcionTareas;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }

    @Override
    public String toString() {
        return "Tarea: " + nombreTareas + ", Descripcion: " + descripcionTareas;
    }




}


